service: serverless-nest-js
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  alb:
    targetGroupPrefix: exchange-product

plugins:
  - serverless-offline

functions:
  api:
    handler: dist/main.handler
    events:
      - httpApi: '*'
